import"./assets/styles-JE8YjOlG.js";import{i as a,a as n}from"./assets/vendor-4yCzdkXl.js";function $(t,o,e){t.forEach(s=>{s.classList.remove(e)}),o.classList.add(e)}function u(t,o="success"){const e={message:t,position:"topRight",timeout:5e3};switch(o){case"success":a.success(e);break;case"error":a.error(e);break;case"warning":a.warning(e);break;default:a.error({message:"Invalid type of toast",position:"topRight",timeout:5e3})}}const c={categoriesList:document.querySelector(".categories"),productsList:document.querySelector(".products"),notFound:document.querySelector(".not-found"),modal:document.querySelector(".modal"),modalCloseButton:document.querySelector(".modal__close-btn"),modalProduct:document.querySelector(".modal-product"),searchForm:document.querySelector(".search-form")};function P(){c.modal.classList.add("modal--is-open"),document.body.style.overflow="hidden",document.addEventListener("keydown",p),c.modal.addEventListener("click",m),c.modalCloseButton.addEventListener("click",d)}function d(){c.modal.classList.remove("modal--is-open"),document.body.style.overflow="",document.removeEventListener("keydown",p),c.modal.removeEventListener("click",m),c.modalCloseButton.removeEventListener("click",d)}function p(t){t.code==="Escape"&&d()}function m(t){t.target.className.includes("modal")&&d()}const E="https://dummyjson.com",r={CATEGORIES:"/products/category-list",PRODUCTS:"/products",PRODUCTS_BY_CATEGORY:"https://dummyjson.com/products/category/",PRODUCT_BY_ID:"/products/",SEARCH:"/products/search?q="};n.defaults.baseURL=E;async function S(){return(await n.get(r.CATEGORIES)).data}async function g(){return(await n.get(r.PRODUCTS)).data}async function w(t){return(await n.get(`${r.PRODUCTS_BY_CATEGORY}${t}`)).data}async function T(t){const o=await n.get(`${r.PRODUCT_BY_ID}${t}`);return console.log(o.data),o.data}async function k(t){const o=await n.get(`${r.SEARCH}${t}`);return console.log(o.data),o.data}function R(t){const e=["All",...t].map(i=>`<li class="categories__item"><button class="categories__btn" type="button">${i}</button></li>
`).join("");c.categoriesList.innerHTML=e,document.querySelector(".categories__btn").classList.add("categories__btn--active")}function l(t){const o=t.map(e=>`<li class="products__item" data-id="${e.id}">
<img class="products__image" src="${e.thumbnail}" alt="${e.title}"/> <p class="products__title"> ${e.title}</p>
<p class="products__brand"><span class="products__brand--bold">Brand: ${e.brand}</span></p>
<p class="products__category">Category: ${e.category}</p> <p class="products__price">Price: ${e.price} $</p> 
</li>`).join("");c.productsList.insertAdjacentHTML("beforeend",o)}function _(){c.productsList.innerHTML=""}function y(){c.notFound.classList.add("not-found--visible")}function f(){c.notFound.classList.remove("not-found--visible")}function A({images:t,title:o,description:e,shippingInformation:s,returnPolicy:i,price:b,thumbnail:I,tags:h}){const L=h.map(C=>`<li>${C}</li>`).join(""),v=`<img class="modal-product__img" src='${t[0]}' alt='${o}' />
   <div class="modal-product__content"> <p class="modal-product__title">${o}</p>
   <ul class="modal-product__tags"> ${L} </ul>
   <p class="modal-product__description">${e}</p>
   <p class="modal-product__shipping-information">Shipping:${s}</p>
   <p class="modal-product__return-policy">Return Policy: ${i}</p>
   <p class="modal-product__price">Price: ${b} $</p>
   <button class="modal-product__buy-btn" type="button">Buy</button> 
   </div>`;c.modalProduct.innerHTML=v}async function B(){try{const t=await S();console.log(t),R(t);const{products:o}=await g();console.log(o),l(o)}catch(t){console.log(`Помилка ініціалізації сторінки Home ${t}`)}}async function O(t){if(t.target.nodeName==="BUTTON"){_();try{const o=t.target.textContent;console.log(o);const e=document.querySelectorAll(".categories__btn");$(e,t.target,"categories__btn--active");let s;o==="All"?s=await g():s=await w(o),console.log(s),s.products.length>0?(f(),l(s.products)):y()}catch(o){console.log(`Помилка отримання товарів по категорії ${o}}`)}}}async function q(t){const o=t.target.closest(".products__item");if(console.log(o.data),!o)return;const e=Number(o.dataset.id),s=await T(e);console.log(s),A(s),P()}async function D(t){t.preventDefault();const o=t.currentTarget.elements.searchValue.value.trim();if(console.log(o),!o){u("Please enter a valid search query","warning");return}_();try{const{products:e}=await k(o);e.length>0?(l(e),f()):y()}catch(e){u(`error get products ${e}`,"error")}}document.addEventListener("DOMContentLoaded",B);c.categoriesList.addEventListener("click",O);c.productsList.addEventListener("click",q);c.searchForm.addEventListener("submit",D);
//# sourceMappingURL=index.js.map
